apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/crider-deployment.yaml
  # - resources/crider-service.yaml
images:
  - name: aws-ecr-development-crider-service
    newName: 795149720653.dkr.ecr.ap-northeast-2.amazonaws.com/aws-ecr-development-crider-service
    newTag: latest
